### ISSUE TITLE
Change font directory?

### ISSUE THREAD

**Issue by SmileYuhao** [ElementUI/element-in-laravel-starter#25]
Hi,

How to change the default **fonts** directory?

After `npm run dev`, it automatically moves **fonts** to the path like:

`public/fonts/vendor/element-ui/packages/theme-default/src/`

**Comment by SmileYuhao** [comment]
I found the solution

* Prevent laravel mix from automatically moving font directory to `public/fonts/vendor/element-ui/packages/theme-default/src/` just set

```javascript
mix.options({
        processCssUrls: false,
});
```

* Set your own font directory path, just add font-face in file `app.scss` (override default), something likes:

```css
@font-face {
  font-family: element-icons;
  src: url(../fonts/element-icons.woff?t=1472440741) format('woff'), 
url(../fonts/element-icons.ttf?t=1472440741) format('truetype');
  font-weight: 400;
  font-style: normal
}
```
